# Site settings
title: dx-deploy
email: mugo@forfuture.co.ke
description: >
  Deploy packages to Dropbox
url: "https://dx-deploy.herokuapp.com/"
baseurl: ""

# Usernames
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
sass:
  style: compressed
