# Site settings
title: dx-deploy
email: mugo@forfuture.co.ke
description: >
  Dropbox as a Package Repository
url: "https://gochomugo.github.io"
baseurl: "/dx-deploy"
comments: true
api_url: "http://dxdeploy-forfuture.rhcloud.com"

# Usernames
twitter_username: GochoMugo
github_username: GochoMugo
disqus_shortname: dxdeploy

# Build settings
markdown: kramdown
sass:
  style: compressed
exclude: ["node_modules/", "script/", "Gruntfile.js", "package.json", ".jshintrc", ".gitignore, ".travis.yml"]

